CREATE TABLE KEYS
(
id   TEXT NOT NULL ,
PRIMARY KEY(id)
) ;

CREATE TABLE LOGS
(
key_id   TEXT NOT NULL ,
value TEXT NOT NULL,
span TEXT NOT NULL,
date    DATE NOT NULL,
FOREIGN KEY(key_id) REFERENCES KEYS(id)
) ;

--First insertions

INSERT INTO KEYS VALUES ("DISTANCE");
INSERT INTO KEYS VALUES ("LUMINOSITY");
INSERT INTO KEYS VALUES ("INTERVAL");
